version: "3.7"

services:
  # myredis:
  #   image: redis

  myvotingapp:
    image: diego/votingapp
    container_name: myvoting_app
    build:
      dockerfile: Dockerfile
      # no es necesario agregar el context
      context: ./src/votingapp
    # environment:
      # REDIS: "myredis:6379"
    networks:
      - votingapp-network

  mynginx:
    image: nginx
    container_name: myvoting_nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - votingapp-network

  mytest:
    image: diego/votingapp-test
    build:
      context: ./test
    container_name: myvoting_test
    environment:
      VOTINGAPP_HOST: "myvotingapp:8080"
    networks:
      - votingapp-network


#Docker Networks
networks:
  votingapp-network:
    driver: bridge
