version: "3.7"

services:
  # myredis:
  #   image: redis

  myvotingapp:
    image: paulopez/votingapp
    build:
      dockerfile: Dockerfile
      # no es necesario agregar el context
      context: ./src/votingapp
    ports: 
      - 80:8080
    # environment:
      # REDIS: "myredis:6379"
    # volumes:
    #   - myapp.conf:/app/myapp.conf
  # mynginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  # mytest:
  #   image: paulopez/votingapp-test
  #   build:
  #     context: ./test
  #   environment:
  #     VOTINGAPP_HOST: "myvotingapp"


# Commands: 
# $ docker-compose build
# $ docker-compose up
# $ 