FROM golang

COPY . .


## dependencies
## si se ponen las dependencias en una línea, se vuelve a pedir, y no obtiene datos de caché
RUN go get github.com/gorilla/websocket
RUN go get github.com/labstack/echo

RUN go build -o ./build ./src/votingapp && \
    cp -r ./src/votingapp/ui ./build